name:                parser-combinator
version:             0.1.0.0
github:              "czipperz/parser-combinator"
license:             BSD3
author:              "Chris Gregory"
maintainer:          "czipperz@gmail.com"
copyright:           "2019 Chris Gregory"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/czipperz/parser-combinator#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  parser-combinator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-combinator

tests:
  parser-combinator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-combinator
    - HUnit
